config/routes.rb
Rails.application.routes.draw do
  #管理者用 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #管理者側namespaceのルーティング
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :show, :update]
    resources :posts, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :destroy]
  end


  #顧客用 URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #顧客側namespaceを含めないルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get '/users/mypage' => 'users#mypage', as: "mypage"
    get '/users/information/edit' => 'users#edit', as: "edit_information"
    patch '/users/information' => 'users#update'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get '/search' => 'searches#search'
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :favorites #いいねしたユーザーを判別するためネスト。判別にidが必要なのでmember
      end
    end
  end

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to:'public/sessions#guest_sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true, uniqueness: true

  scope :only_active, -> { where(is_active: true) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :title
    validates :body
    validates :star
  end

  def self.search(keyword)
    if keyword.present?
      Post.where(['name LIKE ?', "%#{keyword}%"])
    else
      Post.all
    end
  end

  def favorited_by?(user)
    if user.present?
      favorites.exists?(user_id: user.id)
    else
      false
    end
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_relationships, dependent: :destroy
    has_many :posts, through: :tag_relationships

    validates :name, presence: true, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :email, uniqueness: true
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "Guest"
      user.first_name = "User"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ユーザー"
    end
  end

  def self.search(keyword)
    if keyword.present?
      User.where(['CONCAT_WS(" ", last_name, first_name) LIKE ?', "%#{keyword}%"])
    else
      User.all
    end
  end


  def full_name
    (last_name || "") + " " + (first_name || "")
  end

  def full_name_kana
    (last_name_kana || "") + " " + (first_name_kana || "")
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを作成しました。"
    else
      flash.now[:alert] = "ジャンルを作成できませんでした。"
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを編集しました。"
    else
      flash.now[:alert] = "ジャンルを編集できませんでした。"
      render :edit
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path, notice: "ジャンルを削除しました。"
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
    @users = User.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました。"
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def create
    @tag = Tag.new(tag_params)
    @tags = Tag.all
    if @tag.save
      flash[:notice] = "成功"
    else
      flash.now[:alert] = "失敗"
    end
  end

  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def destroy
    @tags = Tag.all
    @tag = Tag.find(params[:id])
    @tag.destroy
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tag_helper.rb
module Admin::TagHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-12">
      <h2 class="text-center mb-4 mt-3">ジャンル編集</h2>
    </div>
  </div>
  <%= render '/layouts/error_messages', post: @genre %>
  <div class="row">
    <div class="col-12 text-center">
    <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
      <div>
        <%= f.label :name, "ジャンル名", class: "ml-2" %>
        <%= f.text_field :name, placeholder: "#{@genre.name}", class: "mx-4 w-25" %>
      	<%= f.radio_button :is_active, true %>
      	<%= f.label :is_active, "有効", class: "ml-2 mr-3" %>
      	<%= f.radio_button :is_active, false %>
      	<%= f.label :is_active, "無効", class: "ml-2 mr-3" %>
      	<%= f.submit "変更を保存", class:"btn btn-sm btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row py-4 pr-3">
    <div class="col-12 text-center mb-3">
      <h2>ジャンル追加</h2>
    </div>
  </div>
  <%= render '/layouts/error_messages', post: @genre %>
  <div class="row">
    <div class="col-12 text-center mb-3">
      <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
        <div>
          <%= f.label :name, "ジャンル名", class: "ml-2" %>
          <%= f.text_field :name, placeholder: "ジャンル名", class: "mx-4 w-25" %>
        	<%= f.radio_button :is_active, true %>
        	<%= f.label :is_active, "有効", class: "mr-2" %>
        	<%= f.radio_button :is_active, false %>
        	<%= f.label :is_active, "無効", class: "mr-3" %>
          <%= f.submit "新規登録", class: "btn btn-sm btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center my-3">
      <h4>登録済みジャンル</h4>
    </div>
  </div>
      <table class="table">
          <th>ジャンル名</th>
          <th>状態</th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td>
              <% if genre.is_active? %>
                <span class="text-success">有効</span>
              <% else %>
                <span class="text-danger">無効</span>
              <% end %>
            </td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-sm btn-success" %></td>
            <th><%= link_to "削除する", admin_genre_path(genre), method: :delete, class: "btn btn-sm btn-danger" %></th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>