config/routes.rb
Rails.application.routes.draw do
  #管理者用 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #管理者側namespaceのルーティング
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :show, :update]
    resources :posts, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :destroy]
  end


  #顧客用 URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #顧客側namespaceを含めないルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get '/users/mypage' => 'users#mypage', as: "mypage"
    get '/users/information/edit' => 'users#edit', as: "edit_information"
    patch '/users/information' => 'users#update'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get '/search' => 'searches#search'
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :favorites #いいねしたユーザーを判別するためネスト。判別にidが必要なのでmember
      end
    end
  end

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to:'public/sessions#guest_sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true, uniqueness: true

  scope :only_active, -> { where(is_active: true) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :title
    validates :body
    validates :star
  end

  def self.search(keyword)
    if keyword.present?
      Post.where(['name LIKE ?', "%#{keyword}%"])
    else
      Post.all
    end
  end

  def favorited_by?(user)
    if user.present?
      favorites.exists?(user_id: user.id)
    else
      false
    end
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_relationships, dependent: :destroy
    has_many :posts, through: :tag_relationships

    validates :name, presence: true, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :email, uniqueness: true
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "Guest"
      user.first_name = "User"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ユーザー"
    end
  end

  def self.search(keyword)
    if keyword.present?
      User.where(['CONCAT_WS(" ", last_name, first_name) LIKE ?', "%#{keyword}%"])
    else
      User.all
    end
  end


  def full_name
    (last_name || "") + " " + (first_name || "")
  end

  def full_name_kana
    (last_name_kana || "") + " " + (first_name_kana || "")
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
    @users = User.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました。"
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def create
    @tag = Tag.new(tag_params)
    @tags = Tag.all
    if @tag.save
      flash[:notice] = "成功"
    else
      flash.now[:alert] = "失敗"
    end
  end

  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def destroy
    @tags = Tag.all
    @tag = Tag.find(params[:id])
    @tag.destroy
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
    @users = User.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "会員情報を編集しました。"
    else
      flash.now[:alert] = "会員情報を編集できませんでした。"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tag_helper.rb
module Admin::TagHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center mb-3">
      <h2>レビュー一覧</h2>
    </div>
  </div>
  <div class="row">
    <% @posts.each do |post| %>
    <div class="col-12 col-md-6 mb-3">
      <div class="card">
        <div class="row no-gutters">
          <div class="col-4">
            <%= image_tag post.get_image(250, 250), class: "img-fluid" %>

              <p class="small-text"><%= @users.find(post.user_id).full_name %>さん</p>
            <p>ジャンル：<%= post.genre.name %></p>
          </div>
          <div class="col-8">
            <div class="card-body">
              <h5 class="card-title"><span class="yellow-bg">商品名: <%= post.name %></span></h5>
              <div>
                <%= render "public/posts/static_rate", post: post %>
              </div>
              <p>一言：<%= post.title %></p>
              <p>商品レビュー：<%= post.body %></p>
              <div class="d-flex align-items-center mt-1">
                <p>
                  <i class="fa-solid fa-heart" style="color: #e54747;"></i> :
                  <%= post.favorites.count %>
                </p>
                <p class="ml-3"><%= "コメント数 : #{post.post_comments.count}" %></p>
              </div>
              <div>
                <div class="col-9">
                  <%= post.tags.pluck(:name).join(' / ') %>
                </div>
              </div>

              <div class="text-right">
                <%= link_to '削除', admin_post_path(post.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: "btn btn-sm btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/tags/_tag_form.html.erb
<%= form_with model: tag, method: :post, url: admin_tags_path, local: false, html: {class: 'p-5 shadow-lg'} do |f| %>
  <div class="form-group">
    <%= f.label :name, 'タグ名', class: 'col-md-2' %>
    <%= f.text_field :name, autofocus: true, autocomplete: 'off', class: 'col-md-6', id: "name_text_field" %>
    <%= f.submit '追加', class: 'btn btn-sm btn-outline-info col-md-2 offset-1' %>
  </div>
<% end %>

app/views/admin/tags/_tag_index.html.erb
<div class="item-wrap row mb-5">
<% tags.each do |tag| %>
  <div class="item shadow-sm col-md-4 p-3 my-3">
    <%= tag.name %>
    <%= link_to admin_tag_path(tag.id), method: :delete, remote: true, style: 'color: red;', 'data-confirm'=>'このタグを削除します' do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
<% end %>
</div>

app/views/admin/tags/create.js.erb
$ (".tag-form").html("<%= j(render 'tag_form', tag: @tag) %>");
$ (".tag-index").html("<%= j(render 'tag_index', tags: @tags) %>");
$ ("#name_text_field").val("");

app/views/admin/tags/destroy.js.erb
$ (".tag-index").html("<%= j(render 'tag_index', tags: @tags) %>");

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row py-4 pr-3">
    <div class="col-12 text-center mb-3">
    <%= render '/layouts/error_messages', post: @tag %>
      <h2>登録済みタグ一覧</h2>
    </div>
  </div>
  <div class="tag-index">
    <%= render 'tag_index', tags: @tags %>
  </div>
  <div class="row">
      <div class="col-12 text-center mb-3">
        <h4>追加登録</h4>
        <div class="tag-form">
          <%= render 'tag_form', tag: @tag %>
        </div>
      </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row py-4 pr-3">
    <div class="col-12 text-center mb-3">
      <h2><%= @user.full_name %>さんの会員情報編集</h2>
    </div>
    </div>
    <%= render '/layouts/error_messages', post: @user %>
    <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">


      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <div class="row">
          <div class="col-4 font-weight-bold">会員ID</div>
          <div class="col-8"><%= @user.id %></div>
        </div>
        <div class="row mt-3">
          <div class="col-4 font-weight-bold">氏名</div>
          <div class="col-4">
            <%= f.label :last_name, "(姓)", class: "sr-only" %>
            <%= f.text_field :last_name, placeholder: "#{@user.last_name}", class: "form-control" %>
          </div>
          <div class="col-4">
            <%= f.label :first_name, "(名)", class: "sr-only" %>
            <%= f.text_field :first_name, placeholder: "#{@user.first_name}", class: "form-control" %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-4 font-weight-bold">フリガナ</div>
          <div class="col-4">
            <%= f.label :last_name_kana, "(セイ)", class: "sr-only" %>
            <%= f.text_field :last_name_kana, placeholder: "#{@user.last_name_kana}", class: "form-control" %>
          </div>
          <div class="col-4">
            <%= f.label :first_name_kana, "(メイ)", class: "sr-only" %>
            <%= f.text_field :first_name_kana, placeholder: "#{@user.first_name_kana}", class: "form-control" %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-4 font-weight-bold">メールアドレス</div>
          <div class="col-8">
            <%= f.text_field :email, placeholder: "#{@user.email}", class: "form-control" %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-4 font-weight-bold">会員ステータス</div>
          <div class="col-4">
            <%= f.radio_button :is_active, true, id: "active_true" %>
            <%= f.label :is_active, "有効", class: "text-success ml-2", for: "active_true" %>
          </div>
          <div class="col-4">
            <%= f.radio_button :is_active, false, id: "active_false" %>
            <%= f.label :is_active, "退会済み", class: "text-danger ml-2", for: "active_false" %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-12 text-center">
            <%= f.submit "変更を保存", class: "btn btn-sm btn-primary px-3" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row py-4 pr-3">
    <div class="col-12 text-center mb-3">
      <h2>会員一覧</h2>
    </div>
  </div>


  <div class="row">
    <div class="col-9 mx-auto">
      <table class='table table-hover table-inverse border-bottom'>
        <thead>
          <th>会員ID</th>
          <th>名前</th>
          <th>フリガナ</th>
          <th>ステータス</th>
          <th></th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.full_name %></td>
              <td><%= user.full_name_kana %></td>
              <td>
                <% if user.is_active? %>
                  <span class="text-success">有効</span>
                <% else %>
                  <span class="text-danger">退会済み</span>
                <% end %>
              </td>
              <td><%= link_to "詳細へ", admin_user_path(user), class: "btn btn-sm btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center mb-3">
      <h2><%= @user.full_name %> さんの会員詳細</h2>
    </div>
    <div class="col-lg-8 col-md-10 col-sm-12 text-center">
      <table class="table table-borderless table-hover">
        <thead>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @user.full_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @user.full_name_kana %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @user.is_active? %>
                <span class="text-success">有効</span>
              <% else %>
                <span class="text-danger">退会済み</span>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "一覧へ戻る", admin_users_path, class: "btn btn-sm btn-primary" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>