config/routes.rb
Rails.application.routes.draw do
  #管理者用 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #管理者側namespaceのルーティング
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :show, :update]
    resources :posts, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :destroy]
  end


  #顧客用 URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #顧客側namespaceを含めないルーティング
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get '/users/mypage' => 'users#mypage', as: "mypage"
    get '/users/information/edit' => 'users#edit', as: "edit_information"
    patch '/users/information' => 'users#update'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get '/search' => 'searches#search'
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show] do
      member do
        get :favorites #いいねしたユーザーを判別するためネスト。判別にidが必要なのでmember
      end
    end
  end

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to:'public/sessions#guest_sign_in'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true, uniqueness: true

  scope :only_active, -> { where(is_active: true) }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :title
    validates :body
    validates :star
  end

  def self.search(keyword)
    if keyword.present?
      Post.where(['name LIKE ?', "%#{keyword}%"])
    else
      Post.all
    end
  end

  def favorited_by?(user)
    if user.present?
      favorites.exists?(user_id: user.id)
    else
      false
    end
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_relationships, dependent: :destroy
    has_many :posts, through: :tag_relationships

    validates :name, presence: true, uniqueness: true
end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :email, uniqueness: true
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "Guest"
      user.first_name = "User"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ユーザー"
    end
  end

  def self.search(keyword)
    if keyword.present?
      User.where(['CONCAT_WS(" ", last_name, first_name) LIKE ?', "%#{keyword}%"])
    else
      User.all
    end
  end


  def full_name
    (last_name || "") + " " + (first_name || "")
  end

  def full_name_kana
    (last_name_kana || "") + " " + (first_name_kana || "")
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def create
    @tag = Tag.new(tag_params)
    @tags = Tag.all
    if @tag.save
      flash[:notice] = "成功"
    else
      flash.now[:alert] = "失敗"
    end
  end

  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def destroy
    @tags = Tag.all
    @tag = Tag.find(params[:id])
    @tag.destroy
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tag_helper.rb
module Admin::TagHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if post.errors.any? %>
  <%= post.errors.count %>件のエラーが発生しました
  <ul>
    <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, placeholder: 'キーワードから探す' %>
    <%= f.select :range, options_for_select([['投稿', "Post"],['ユーザー', "User"]]) %>
    <%= f.button :submit, class: "btn btn-sm btn-warning rounded-pill" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PapaPreview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8ce2afc576.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg" style="background-color: #F4EFEC;">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div>
            <%= link_to admin_signed_in? ? admin_top_path : root_path do %>
              <%= image_tag "logo.png", size: "200x200", class: "navbar-brand p-3" %>
            <% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!-- 会員がログインした時の表示 -->
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "マイページ", mypage_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規投稿", new_post_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "みんなの投稿", posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "いいねした投稿", favorites_user_path(current_user), class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ユーザー一覧", users_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>

              <!-- 管理者がログインした時の表示 -->
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark border rounded mr-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark border rounded mx-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "レビュー一覧", admin_posts_path, class: 'nav-link text-dark border rounded mx-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link text-dark border rounded mx-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border rounded ml-2' %>
                </li>
                <!-- ログアウトした時の表示 -->
              <% else %>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "みんなの投稿", posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員登録", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to '管理者ログイン', new_admin_session_path, class: "nav-link text-dark" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container d-flex wrap">
        <div class="col-4 ml-4">
          <!-- 会員がログインしている時、ログイン中の会員の氏名を表示 -->
          <% if user_signed_in? %>
            <p class="ml-4">ようこそ、<%= current_user.last_name %>さん！</p>
          <% end %>
        </div>
        <div class="col-7 offset-1 mb-2 d-flex justify-content-end">
          <%= render partial: 'layouts/form' %>
        </div>
      </div>
    </header>
    <main class="bg  pb-5" style="background-color: #F4EFEC;">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer class="d-flex justify-content-center align-items-center p-5 bg text-light" style="background-color: #736A63;">Copyright © 2024. Papa_Preview.</footer>
  </body>
</html>